name: fcm_localization
description: Package that depends on fcm_config package to localize firbasemessaging notifications
version: 1.0.2
homepage: https://github.com/mo-ah-dawood/fcm_config/tree/master/fcm_localization

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fcm_config: '>=3.0.4 <4.0.0'
  shared_preferences: '>=2.0.5 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

