name: fcm_config
description: This flutter package is made to merge between firebase_messaging package and flutter_local_notifications
version: 3.6.5

homepage: https://github.com/mu-dawood/fcm_config
repository: https://github.com/mu-dawood/fcm_config

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: '>=3.6.0 <5.0.0'
  firebase_messaging: '>=15.1.3 <20.0.0'
  flutter_local_notifications: '>=17.2.3 <20.0.0'
  plugin_platform_interface: '>=2.1.8 <3.0.0'
  http: '>=1.2.2 <3.0.0'
  web: '>=1.1.0 <2.0.0'
  path_provider: '>=2.1.4 <5.0.0'

dev_dependencies:
  flutter_lints: ^5.0.0

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/web/firebase-messaging-sw.js
  - /example/lib/firebase_options.dart
  - /example/web/index.html
